### ISSUE TITLE
cmake failed

### ISSUE THREAD

**Issue by abdulrahmanmadeni** [xpol/lua-rapidjson#10]
Try to clone the codes using git, but we got error message.... "failed to cmake"

**Comment by xpol** [comment]
Would you please paste the full cmake log please?

**Comment by abdulrahmanmadeni** [comment]
Hi

this is the pull cmake log after I submit command " luarocks install
rapidjson":

Archive:
/tmp/luarocks_luarocks-rock-rapidjson-0.3.1-1-7779/rapidjson-0.3.1-1.src.rock
  inflating: rapidjson-0.3.1-1.rockspec
   creating: lua-rapidjson/
   creating: lua-rapidjson/.scripts/
  inflating: lua-rapidjson/.scripts/install.bat
  inflating: lua-rapidjson/.scripts/platform.sh
  inflating: lua-rapidjson/.scripts/set_compiler_env.bat
  inflating: lua-rapidjson/.scripts/setenv_lua.sh
  inflating: lua-rapidjson/.scripts/setup_lua.sh
  inflating: lua-rapidjson/.scripts/winmake.bat
  inflating: lua-rapidjson/.travis.yml
  inflating: lua-rapidjson/appveyor.yml
  inflating: lua-rapidjson/CMakeLists.txt
  inflating: lua-rapidjson/LICENSE
   creating: lua-rapidjson/performance/
  inflating: lua-rapidjson/performance/booleans.json
  inflating: lua-rapidjson/performance/floats.json
  inflating: lua-rapidjson/performance/guids.json
  inflating: lua-rapidjson/performance/integers.json
  inflating: lua-rapidjson/performance/mixed.json
  inflating: lua-rapidjson/performance/nulls.json
  inflating: lua-rapidjson/performance/paragraphs.json
  inflating: lua-rapidjson/performance/run.lua
   creating: lua-rapidjson/rapidjson/
  inflating: lua-rapidjson/rapidjson/.gitignore
  inflating: lua-rapidjson/rapidjson/.gitmodules
  inflating: lua-rapidjson/rapidjson/.travis.yml
  inflating: lua-rapidjson/rapidjson/appveyor.yml
   creating: lua-rapidjson/rapidjson/bin/
   creating: lua-rapidjson/rapidjson/bin/data/
  inflating: lua-rapidjson/rapidjson/bin/data/glossary.json
  inflating: lua-rapidjson/rapidjson/bin/data/menu.json
  inflating: lua-rapidjson/rapidjson/bin/data/readme.txt
  inflating: lua-rapidjson/rapidjson/bin/data/sample.json
  inflating: lua-rapidjson/rapidjson/bin/data/webapp.json
  inflating: lua-rapidjson/rapidjson/bin/data/widget.json
   creating: lua-rapidjson/rapidjson/bin/encodings/
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf16be.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf16bebom.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf16le.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf16lebom.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf32be.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf32bebom.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf32le.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf32lebom.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf8.json
  inflating: lua-rapidjson/rapidjson/bin/encodings/utf8bom.json
   creating: lua-rapidjson/rapidjson/bin/jsonchecker/
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail1.json
  inflating: lua-rapidjson/rapidjson/bin/jsonchecker/fail10.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail11.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail12.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail13.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail14.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail15.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail16.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail17.json
  inflating: lua-rapidjson/rapidjson/bin/jsonchecker/fail18.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail19.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail2.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail20.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail21.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail22.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail23.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail24.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail25.json
  inflating: lua-rapidjson/rapidjson/bin/jsonchecker/fail26.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail27.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail28.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail29.json
  inflating: lua-rapidjson/rapidjson/bin/jsonchecker/fail3.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail30.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail31.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail32.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail33.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail4.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail5.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail6.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail7.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail8.json
 extracting: lua-rapidjson/rapidjson/bin/jsonchecker/fail9.json
  inflating: lua-rapidjson/rapidjson/bin/jsonchecker/pass1.json
  inflating: lua-rapidjson/rapidjson/bin/jsonchecker/pass2.json
  inflating: lua-rapidjson/rapidjson/bin/jsonchecker/pass3.json
  inflating: lua-rapidjson/rapidjson/bin/jsonchecker/readme.txt
  inflating: lua-rapidjson/rapidjson/CHANGELOG.md
  inflating: lua-rapidjson/rapidjson/CMakeLists.txt
   creating: lua-rapidjson/rapidjson/CMakeModules/
  inflating: lua-rapidjson/rapidjson/CMakeModules/FindGTestSrc.cmake
   creating: lua-rapidjson/rapidjson/doc/
  inflating: lua-rapidjson/rapidjson/doc/CMakeLists.txt
   creating: lua-rapidjson/rapidjson/doc/diagram/
  inflating: lua-rapidjson/rapidjson/doc/diagram/architecture.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/architecture.png
  inflating: lua-rapidjson/rapidjson/doc/diagram/insituparsing.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/insituparsing.png
  inflating:
lua-rapidjson/rapidjson/doc/diagram/iterative-parser-states-diagram.dot
  inflating:
lua-rapidjson/rapidjson/doc/diagram/iterative-parser-states-diagram.png
  inflating: lua-rapidjson/rapidjson/doc/diagram/makefile
  inflating: lua-rapidjson/rapidjson/doc/diagram/move1.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/move1.png
  inflating: lua-rapidjson/rapidjson/doc/diagram/move2.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/move2.png
  inflating: lua-rapidjson/rapidjson/doc/diagram/move3.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/move3.png
  inflating: lua-rapidjson/rapidjson/doc/diagram/normalparsing.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/normalparsing.png
  inflating: lua-rapidjson/rapidjson/doc/diagram/simpledom.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/simpledom.png
  inflating: lua-rapidjson/rapidjson/doc/diagram/tutorial.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/tutorial.png
  inflating: lua-rapidjson/rapidjson/doc/diagram/utilityclass.dot
  inflating: lua-rapidjson/rapidjson/doc/diagram/utilityclass.png
  inflating: lua-rapidjson/rapidjson/doc/dom.md
  inflating: lua-rapidjson/rapidjson/doc/dom.zh-cn.md
  inflating: lua-rapidjson/rapidjson/doc/Doxyfile.in
  inflating: lua-rapidjson/rapidjson/doc/Doxyfile.zh-cn.in
  inflating: lua-rapidjson/rapidjson/doc/encoding.md
  inflating: lua-rapidjson/rapidjson/doc/encoding.zh-cn.md
  inflating: lua-rapidjson/rapidjson/doc/faq.md
  inflating: lua-rapidjson/rapidjson/doc/faq.zh-cn.md
  inflating: lua-rapidjson/rapidjson/doc/features.md
  inflating: lua-rapidjson/rapidjson/doc/features.zh-cn.md
  inflating: lua-rapidjson/rapidjson/doc/internals.md
   creating: lua-rapidjson/rapidjson/doc/logo/
 extracting: lua-rapidjson/rapidjson/doc/logo/rapidjson.png
  inflating: lua-rapidjson/rapidjson/doc/logo/rapidjson.svg
   creating: lua-rapidjson/rapidjson/doc/misc/
  inflating: lua-rapidjson/rapidjson/doc/misc/doxygenextra.css
  inflating: lua-rapidjson/rapidjson/doc/misc/DoxygenLayout.xml
  inflating: lua-rapidjson/rapidjson/doc/misc/footer.html
  inflating: lua-rapidjson/rapidjson/doc/misc/header.html
  inflating: lua-rapidjson/rapidjson/doc/performance.md
  inflating: lua-rapidjson/rapidjson/doc/performance.zh-cn.md
  inflating: lua-rapidjson/rapidjson/doc/pointer.md
  inflating: lua-rapidjson/rapidjson/doc/pointer.zh-cn.md
  inflating: lua-rapidjson/rapidjson/doc/sax.md
  inflating: lua-rapidjson/rapidjson/doc/sax.zh-cn.md
  inflating: lua-rapidjson/rapidjson/doc/stream.md
  inflating: lua-rapidjson/rapidjson/doc/stream.zh-cn.md
  inflating: lua-rapidjson/rapidjson/doc/tutorial.md
  inflating: lua-rapidjson/rapidjson/doc/tutorial.zh-cn.md
   creating: lua-rapidjson/rapidjson/example/
   creating: lua-rapidjson/rapidjson/example/capitalize/
  inflating: lua-rapidjson/rapidjson/example/capitalize/capitalize.cpp
  inflating: lua-rapidjson/rapidjson/example/CMakeLists.txt
   creating: lua-rapidjson/rapidjson/example/condense/
  inflating: lua-rapidjson/rapidjson/example/condense/condense.cpp
   creating: lua-rapidjson/rapidjson/example/messagereader/
  inflating:
lua-rapidjson/rapidjson/example/messagereader/messagereader.cpp
   creating: lua-rapidjson/rapidjson/example/pretty/
  inflating: lua-rapidjson/rapidjson/example/pretty/pretty.cpp
   creating: lua-rapidjson/rapidjson/example/prettyauto/
  inflating: lua-rapidjson/rapidjson/example/prettyauto/prettyauto.cpp
   creating: lua-rapidjson/rapidjson/example/serialize/
  inflating: lua-rapidjson/rapidjson/example/serialize/serialize.cpp
   creating: lua-rapidjson/rapidjson/example/simpledom/
  inflating: lua-rapidjson/rapidjson/example/simpledom/simpledom.cpp
   creating: lua-rapidjson/rapidjson/example/simplereader/
  inflating: lua-rapidjson/rapidjson/example/simplereader/simplereader.cpp
   creating: lua-rapidjson/rapidjson/example/simplewriter/
  inflating: lua-rapidjson/rapidjson/example/simplewriter/simplewriter.cpp
   creating: lua-rapidjson/rapidjson/example/tutorial/
  inflating: lua-rapidjson/rapidjson/example/tutorial/tutorial.cpp
   creating: lua-rapidjson/rapidjson/include/
   creating: lua-rapidjson/rapidjson/include/rapidjson/
  inflating: lua-rapidjson/rapidjson/include/rapidjson/allocators.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/document.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/encodedstream.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/encodings.h
   creating: lua-rapidjson/rapidjson/include/rapidjson/error/
  inflating: lua-rapidjson/rapidjson/include/rapidjson/error/en.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/error/error.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/filereadstream.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/filewritestream.h
   creating: lua-rapidjson/rapidjson/include/rapidjson/internal/
  inflating:
lua-rapidjson/rapidjson/include/rapidjson/internal/biginteger.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/diyfp.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/dtoa.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/ieee754.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/itoa.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/meta.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/pow10.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/stack.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/strfunc.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/strtod.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/internal/swap.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/memorybuffer.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/memorystream.h
   creating: lua-rapidjson/rapidjson/include/rapidjson/msinttypes/
  inflating:
lua-rapidjson/rapidjson/include/rapidjson/msinttypes/inttypes.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/msinttypes/stdint.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/pointer.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/prettywriter.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/rapidjson.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/reader.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/stringbuffer.h
  inflating: lua-rapidjson/rapidjson/include/rapidjson/writer.h
  inflating: lua-rapidjson/rapidjson/library.json
  inflating: lua-rapidjson/rapidjson/license.txt
  inflating: lua-rapidjson/rapidjson/rapidjson.autopkg
  inflating: lua-rapidjson/rapidjson/RapidJSON.pc.in
  inflating: lua-rapidjson/rapidjson/RapidJSONConfig.cmake.in
  inflating: lua-rapidjson/rapidjson/RapidJSONConfigVersion.cmake.in
  inflating: lua-rapidjson/rapidjson/readme.md
  inflating: lua-rapidjson/rapidjson/readme.zh-cn.md
   creating: lua-rapidjson/rapidjson/test/
  inflating: lua-rapidjson/rapidjson/test/CMakeLists.txt
   creating: lua-rapidjson/rapidjson/test/perftest/
  inflating: lua-rapidjson/rapidjson/test/perftest/CMakeLists.txt
  inflating: lua-rapidjson/rapidjson/test/perftest/misctest.cpp
  inflating: lua-rapidjson/rapidjson/test/perftest/perftest.cpp
  inflating: lua-rapidjson/rapidjson/test/perftest/perftest.h
  inflating: lua-rapidjson/rapidjson/test/perftest/platformtest.cpp
  inflating: lua-rapidjson/rapidjson/test/perftest/rapidjsontest.cpp
   creating: lua-rapidjson/rapidjson/test/unittest/
  inflating: lua-rapidjson/rapidjson/test/unittest/allocatorstest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/bigintegertest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/CMakeLists.txt
  inflating: lua-rapidjson/rapidjson/test/unittest/documenttest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/encodedstreamtest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/encodingstest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/filestreamtest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/itoatest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/jsoncheckertest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/namespacetest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/pointertest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/prettywritertest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/readertest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/simdtest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/stringbuffertest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/strtodtest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/unittest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/unittest.h
  inflating: lua-rapidjson/rapidjson/test/unittest/valuetest.cpp
  inflating: lua-rapidjson/rapidjson/test/unittest/writertest.cpp
  inflating: lua-rapidjson/rapidjson/travis-doxygen.sh
  inflating: lua-rapidjson/rapidjson-0.3.1-1.rockspec
  inflating: lua-rapidjson/README.md
   creating: lua-rapidjson/spec/
 extracting: lua-rapidjson/spec/empty-array.json
 extracting: lua-rapidjson/spec/empty-file.json
 extracting: lua-rapidjson/spec/empty-object.json
  inflating: lua-rapidjson/spec/json_array_spec.lua
  inflating: lua-rapidjson/spec/json_decode_spec.lua
  inflating: lua-rapidjson/spec/json_dump_spec.lua
  inflating: lua-rapidjson/spec/json_encode_spec.lua
  inflating: lua-rapidjson/spec/json_load_spec.lua
  inflating: lua-rapidjson/spec/json_null_spec.lua
  inflating: lua-rapidjson/spec/json_object_spec.lua
   creating: lua-rapidjson/src/
  inflating: lua-rapidjson/src/rapidjson.cpp
Installing
http://luarocks.org/repositories/rocks/rapidjson-0.3.1-1.src.rock...
Using http://luarocks.org/repositories/rocks/rapidjson-0.3.1-1.src.rock...
switching to 'build' mode

sh:    1: cmake: not found

Error: Build error: Failed cmake

**Comment by miloyip** [comment]
Download and install [cmake](https://cmake.org/download/)

**Comment by abdulrahmanmadeni** [comment]
OK... let me try first

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by xpol** [comment]
@abdulrahmanmadeni 
Yes according to your error log, it seems you don't have cmake installed.

BTW, I have just released 0.4.0-1 in luarocks.

@miloyip
Thank you!

**Comment by xpol** [comment]
@abdulrahmanmadeni 
Does it fixes the issue after install camke and put it in your path?

**Comment by abdulrahmanmadeni** [comment]
Yes. Thank you for your help
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by xpol** [comment]
so close this issue.
Thank you!
