### ISSUE TITLE
Wait next RapidJSON release for fixes NaN encoding.

### ISSUE THREAD

**Issue by xpol** [xpol/lua-rapidjson#11]
(Moved form https://github.com/xpol/lua-rapidjson/issues/9#issuecomment-176703441)
NaN encoding, i.e. encode(0/0), is not throwing an error (nil + error message).
I expected so according to: miloyip/rapidjson#509

**Comment by stepelu** [comment]
I thought this had been done already in https://github.com/xpol/lua-rapidjson/commit/1f37cec53f43f7309952317b5d343637d9d67c0e (see "ad1d22e Fix #509 by checking Nan/Inf when writing a double") ?

**Comment by xpol** [comment]
Yes it still result `2.696539702293474e308`:


    LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
    JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse 
    > j = require('rapidjson')
    > print(j.encode(0/0))
    2.696539702293474e308

**Comment by miloyip** [comment]
Strange... BTW, I think it is needed to check the return `bool` of `Double`, and raise error in Lua.

**Comment by xpol** [comment]
It does not return `false` when encoding `0/0` in lua.

**Comment by miloyip** [comment]
Yes. I have asked GitHub support that recently some PR was merged but the commit was lost in the history.

**Comment by miloyip** [comment]
I have got one e-mail but the admin don't think there is problem.
I manually cherry-pick the merge again and it should be in the master.
https://github.com/miloyip/rapidjson/blob/master/include/rapidjson/writer.h#L245

**Comment by xpol** [comment]
Updated and tested in commit 7918f5b837c18dc68e3970c3cfb52c992bb67c54.
