### ISSUE TITLE
luarocks install rapidjson buided failed on windows7 64bit

### ISSUE THREAD

**Issue by sandogeek** [xpol/lua-rapidjson#17]
The output:
```
C:\Users\sandogeek>luarocks install rapidjson
Installing http://luarocks.org/repositories/rocks/rapidjson-0.5.0-1.src.rock...
Warning: unmatched variable LUALIB
-- The C compiler identification is GNU 4.7.1
-- The CXX compiler identification is GNU 4.7.1
-- Check for working C compiler: D:/ST3ALL/MinGW/bin/gcc.exe
-- Check for working C compiler: D:/ST3ALL/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/ST3ALL/MinGW/bin/g++.exe
-- Check for working CXX compiler: D:/ST3ALL/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- LUA_RAPIDJSON_VERSION: 0.5.0
-- Configuring done
WARNING: Target "lua-rapidjson" requests linking to directory "G:/Program Files
(x86)/Lua/5.1/lib/".  Targets may link only to libraries.  CMake is dropping the
 item.
-- Generating done
-- Build files have been written to: C:/Users/sandogeek/AppData/Local/Temp/luaro
cks_rapidjson-0.5.0-1-2092/lua-rapidjson
'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

Error: Build error: Failed building.
```
"'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件。" means "'make' is neither internal or external command,or execuable or bat file.

**Comment by xpol** [comment]
you need make to build under MinGW.
sandogeek <notifications@github.com>于2017年1月14日 周六下午6:47写道：

**Comment by sandogeek** [comment]
How to cofigure it when I an willing to use luarocks to install rapidjson?

**Comment by xpol** [comment]
install make for your MinGW, and try again.

Or use LuaVM https://github.com/xpol/luavm if you have visual studio
installed.
sandogeek <notifications@github.com>于2017年1月14日 周六下午8:35写道：

**Comment by sandogeek** [comment]
I can't find a tutorial about installing make for MinGW,it seems that MinGW use mingw32-make.exe instead.I don't know how to replace make with that.
And is that I install LuaVM,and than run `luarocks install rapidjson`,this issue will be solved.

**Comment by xpol** [comment]
Is your luarocks configured correctly with MinGW? for luarocks support please goto https://github.com/luarocks/luarocks
Is your Lua build with MinGW?

**Comment by sandogeek** [comment]
I set luarocks `local USE_MINGW = true`,but the issue still exists.Is there something like rapidjson.dll which is out-of-box since I am not insteresting in compiling it by myself.
