### ISSUE TITLE
error when make 

### ISSUE THREAD

**Issue by wangyinsheng** [xpol/lua-rapidjson#21]
> [root@bogon lua-rapidjson]# cmake ./
-- LUA_RAPIDJSON_VERSION: v0.5.0-3-gaf52bc3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/silver/Desktop/lua-rapidjson
[root@bogon lua-rapidjson]# make
[ 20%] Building CXX object CMakeFiles/lua-rapidjson.dir/src/Document.cpp.o
In file included from /home/silver/Desktop/lua-rapidjson/src/Document.cpp:13:
/home/silver/Desktop/lua-rapidjson/src/Userdata.hpp: In static member function ‘static T* Userdata<T>::get(lua_State*, int)’:
/home/silver/Desktop/lua-rapidjson/src/Userdata.hpp:49: error: ‘nullptr’ was not declared in this scope
/home/silver/Desktop/lua-rapidjson/src/Userdata.hpp:58: error: ‘nullptr’ was not declared in this scope
/home/silver/Desktop/lua-rapidjson/src/Userdata.hpp: In static member function ‘static int Userdata<T>::metamethod_gc(lua_State*)’:
/home/silver/Desktop/lua-rapidjson/src/Userdata.hpp:72: error: ‘nullptr’ was not declared in this scope
/home/silver/Desktop/lua-rapidjson/src/Document.cpp: In static member function ‘static T* Userdata<T>::construct(lua_State*) [with T = rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>]’:
/home/silver/Desktop/lua-rapidjson/src/Document.cpp:34: error: ‘nullptr’ was not declared in this scope
/home/silver/Desktop/lua-rapidjson/src/Document.cpp: In static member function ‘static const luaL_Reg* Userdata<T>::methods() [with T = rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>]’:
/home/silver/Desktop/lua-rapidjson/src/Document.cpp:182: error: ‘nullptr’ was not declared in this scope
make[2]: *** [CMakeFiles/lua-rapidjson.dir/src/Document.cpp.o] Error 1
make[1]: *** [CMakeFiles/lua-rapidjson.dir/all] Error 2
make: *** [all] Error 2
[root@bogon lua-rapidjson]# 

here is cmake version and gcc version
> [root@bogon lua-rapidjson]# cmake --version
cmake version 3.8.0-rc3
CMake suite maintained and supported by Kitware (kitware.com/cmake).
[root@bogon lua-rapidjson]# gcc --version
gcc (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by xpol** [comment]
I have removed most all c++11 feature requirements in b7f38a9 .
Current lua-rapidjson only requires support move constructor.


Try  the HEAD version.

**Comment by wangyinsheng** [comment]
it works，thanks a lot！
