### ISSUE TITLE
Json encode integer to double number

### ISSUE THREAD

**Issue by Progmdong** [xpol/lua-rapidjson#22]
I have tried to encode a table, but it seems integer has been encode to double number, working on Windows7 x64, Lua5.1.
Example: 
     json.encode( {id=7, method="CreateEntity".... } )
   result:
     {"id":7.00000000003178,"method":"CreateEntity",.....

**Comment by jmealo** [comment]
@progmdong were you able to resolve this issue?

**Comment by xpol** [comment]
I have added [a test case](https://github.com/xpol/lua-rapidjson/commit/10c5202dfaa33a876ec6a9163c72301bba594a5c) for this, it [passed](https://travis-ci.org/xpol/lua-rapidjson/builds/447425813).
