### ISSUE TITLE
Option to encode empty table as array

### ISSUE THREAD

**Issue by stuta** [xpol/lua-rapidjson#23]
Hello.

Is it possible for empty Lua tables {} to return "[]" instead of "{}"?
Lua cjson has this option: cjson.encode_empty_table_as_object(false). I can use __jsontype, but then I would need to attach it to all possible deep elements.

I mean {a={}} => {"a": []}.

**Comment by xpol** [comment]
Noted and work in progress. Hold on.

**Comment by stuta** [comment]
Thanks!

I think the detection code "if something is an array" is not correct. 
{"asd", c=2} should give (like in cjson) => {"1": "asd", "c": 2}, not ["asd"]. It's ok for me if this is an option too. I'm sure the detection  code will be found from cjson.

**Comment by xpol** [comment]
It is just a choice. For any non empty table with length > 0, will treat as array.
That is lua-rapidjson is currently not support mixed hash and array tables.

**Comment by xpol** [comment]
ccd02f2 Added empty_table_as_array option for rapidjson.encode(). You can have it a try.

**Comment by stuta** [comment]
Thanks, I'll try later.

If this does not not support mixed hash and array tables (separate option is ok), then I can't replace cjson with lua-rapidjson. This is not  compatible with any other lua json library.

**Comment by stuta** [comment]
I tested this with nested arrays, it works. I think I can use this in most-used user case: sending json from my luajit server to browser. I know that I do not have mixed json there.

**Comment by stuta** [comment]
I changed in pretty json 4 spaces to one tab (saves space in big json):
    if (pretty)
    {
      PrettyWriter<Stream> writer(*s);
      writer.SetIndent('\t', 1);
      encodeValue(L, &writer, idx);
    }

I had some trouble to change CMakeLists.txt to use sse2 or sse4.2 (osx, win and linux), if somebody needs info I can give it.

This library is really fast, first one to beat cjson (and msgpack). Thanks again!
