### ISSUE TITLE
Exception occurred when call rapidjson.encode(param) where a function in the "param"

### ISSUE THREAD

**Issue by pcloves** [xpol/lua-rapidjson#28]
hi, there is a annoying trouble i cant handle with, when i call rapidjson.encode(param) where a function is in the "param", a exception happens. how can i avoid this exception, thanks a lot.

call stack log list as follow:
=================================================
XLuaManager DoString(GameMain.StartGame()) - Exception Info:Project/Behavior/Core/ProcessorUnit:92: value type : function
stack traceback:
	[C]: in function 'rapidjson.encode'
	Project/Behavior/Core/ProcessorUnit:92: in local 'action'
	Common/Collections/LuaList:259: in function 'Common.Collections.LuaList.ForEach'
	Project/Behavior/Core/ProcessorUnit:90: in local 'action'
	Common/Collections/LuaList:259: in function 'Common.Collections.LuaList.ForEach'
	Project/Behavior/Core/ProcessorUnit:41: in function

**Comment by xpol** [comment]
Please make sure you have pure data that json support in `param`.
