### ISSUE TITLE
why need cmake > =3.1?

### ISSUE THREAD

**Issue by moonming** [xpol/lua-rapidjson#37]
https://github.com/xpol/lua-rapidjson/blob/master/CMakeLists.txt#L1
Does compiling with the version of cmake 2.x cause any problems? Because most systems don't have cmake3.
 thanks.

**Comment by moonming** [comment]
thanks for your quick response: https://github.com/xpol/lua-rapidjson/commit/0deb81e6cd2ab8171763e6b34b18ec54b8107d3a.
@xpol Could you please update the version on Luarocks? thank you.

**Comment by xpol** [comment]
@moonming Released v0.6.0 to luarocks.org.
