### ISSUE TITLE
Windows 64 bit build

### ISSUE THREAD

**Issue by starius** [xpol/lua-rapidjson#4]
lua-rapidjson can not be built under Windows 64 bit in Appveyor

I installed it for testing purposes in [my project](https://github.com/starius/single-dir.lua) in [Appveyor](https://ci.appveyor.com/project/starius/single-dir-lua/build/0.0.1.9-test).

[x86 version](https://ci.appveyor.com/project/starius/single-dir-lua/build/job/9sgul9ry96ce3mua) can be built, but [64 bit version](https://ci.appveyor.com/project/starius/single-dir-lua/build/job/gx8llg70f6nlwbmv) fails.

One of error messages:
```
rapidjson.obj : error LNK2019: unresolved external symbol _lua_pushfstring referenced in
 function "int __cdecl decode<struct rapidjson::GenericStringStream<struct rapidjson::UTF8
<char> > >(struct lua_State *,struct rapidjson::GenericStringStream<struct rapidjson::UTF8
<char> > *)" 
```

**Comment by xpol** [comment]
Sorry too late back to here.

lua-rapidjson use luarocks and cmake to build.

but luarocks does not have 64 bit cmake build support yet. And have reported here keplerproject/luarocks/issues/382

you may need to use cmake directly:

1. checkout lua-rapidjson
2. in the lua-rapidjson porject root run `cmake -H. -Bbuild.luarocks -G Visual Studio 2013 Win64`
3. install the result manually

**Comment by starius** [comment]
Thank you!

**Comment by ignacio** [comment]
I'm working on a PR for LuaRocks to address this issue.

**Comment by ignacio** [comment]
Here is a build using my proposed PR:

https://ci.appveyor.com/project/ignacio/lua-rapidjson/build/0.1.0.12

It passes for x86, it fails for x64 but it is something related to busted. If you see, lua-rapidjson is being compiled as 64 bits.

**Comment by ignacio** [comment]
BTW, the PR is [here](https://github.com/keplerproject/luarocks/pull/383).

**Comment by xpol** [comment]
@ignacio Thank you very much!

**Comment by ignacio** [comment]
@xpol A fix has landed on LuaRocks allowing to build with cmake on x64. It is on the scm version but I presume there is gonna be a new release sometime soon.

**Comment by xpol** [comment]
@ignacio Great! Thank you very much.
