### ISSUE TITLE
Adding data to decoded empty table produce no change when encode again

### ISSUE THREAD

**Issue by AlexanderMisel** [xpol/lua-rapidjson#43]
Version: Lua 5.1 on Windows x86
Steps to reproduce: Run the following program
```lua
local json = require('rapidjson')

local a = {}

local str = json.encode(a)
a = json.decode(str)
print(json.encode(a))

a[1] = 'def'

print(json.encode(a))
```
Output
```
{}
{}
```
Expected output
```
{}
["def"]
```

**Comment by xpol** [comment]
Because the `a` deocded from str has metatable `{__jsontype= 'object'}`. This tells lua rapdijson that the table should always tread as json object.

> json = require('rapidjson')
> a = {}
> str = json.encode(a)
> a = json.decode(str)
> t = getmetatable(a)
> t.__jsontype
object
>

**Comment by AlexanderMisel** [comment]
@xpol So why didn't rapdjson handle this? How can I re-encode it as JSON string? The cjson module handles the case as well, as produced expected output.

**Comment by AlexanderMisel** [comment]
I mean, why not simply remove the metatable `__jsontype` before passing to Lua? It will be more convenient, and will still auto detect it is an object or array.

**Comment by xpol** [comment]
Modify your code.

```lua
local a = {}
```

to 
```
local a = rapidjson.array()
```

the a will be always be treated as array.

**Comment by AlexanderMisel** [comment]
But still, this would lose generality, to switch from libraries... Well thanks.

**Comment by xpol** [comment]
JSON [] is not JSON {}.

Did you mean got a JSON empty object decoded into a Lua table and you want
later encode it as array?

Best Regards!

Xpol Wan
// There is a better way!

**Comment by AlexanderMisel** [comment]
> Did you mean got a JSON empty object decoded into a Lua table and you want
later encode it as array?
Yes! That's it. If could be so.

**Comment by xpol** [comment]
setmetatable(a, nil)


发自我的 iPhone
