### ISSUE TITLE
rapidjson.Document seems to not be freed correctly

### ISSUE THREAD

**Issue by jbchouinard** [xpol/lua-rapidjson#45]
Lua 5.3.5
rapidjson 0.6.1-1

```lua
local rapidjson = require("rapidjson")

local N = 10000000

local function main()
	for _ = 0, N do
		local d = rapidjson.Document("{ 'foo': 'bar' }")
		d = nil
	end
end

print(collectgarbage("count"))
main()
print(collectgarbage("count"))
collectgarbage()
print(collectgarbage("count"))
collectgarbage()
print(collectgarbage("count"))
io.read()
```

The garbage collector claims that Lua is using almost not memory after `collectgarbage()`, but using a tool like htop, you can see the process's resident memory usage does not go down (~1GB with this example on my machine, can make it arbitrarily high by increasing `N`).

**Comment by jbchouinard** [comment]
The problem seems to occur when creating `Document` from nothing or a string, but not when created from a table:

Problem:
```lua
local d = rapidjson.Document("{'foo': 'bar'}")
local d = rapidjson.Document()
```

No problem:
```lua
local d = rapidjson.Document({foo='bar'})
```

**Comment by jbchouinard** [comment]
The problem also occurs with `SchemaDocument`too. And I was wrong about it not happening when created from a table, I see negligible memory use if created from a simple table literal but the problem occurs when using a larger table.

**Comment by xpol** [comment]
Activity Manager tells me the memory has get freed.

![memory](https://user-images.githubusercontent.com/20248/75606510-7bad5d00-5b28-11ea-84ee-5d09b2bb2d0d.png)

**Comment by xpol** [comment]
And same result with htop.
