### ISSUE TITLE
lua-rapidjson dump 可以往别的路径写入文件么

### ISSUE THREAD

**Issue by Zoe0208** [xpol/lua-rapidjson#51]
我是用Unity xlua开发的
lua-rapidjson dump 可以往别的路径写入文件么（比如沙盒）,默认只传文件名会生成在Assets同级目录，我传路径的话会报错

LuaException: GameSaveData/GameSaveDataTest:9: error while open file: C:/Users/user/AppData/LocalLow/XP/xpgame/Game/Test.json

**Comment by xpol** [comment]
encode 得到内容自己写文件，
