### ISSUE TITLE
Update build scripts

### ISSUE THREAD

**Issue by ignacio** [xpol/lua-rapidjson#6]
Hi! As mentioned in https://github.com/keplerproject/luarocks/issues/382, there is [a fix](https://github.com/ignacio/lua-appveyor-example/commit/a3daab5e9e9553e8f7336eae139e032635f15ae1) to the appveyor install script. You might want to apply the fix to your script by hand, or you might want to update the whole appveyor integration.

Here is [a job](https://ci.appveyor.com/project/ignacio/lua-appveyor-example/build/0.0.1.150-test) that installed busted correctly (but failed because I don't have any test file tu run).

**Comment by ignacio** [comment]
I see you've updated the scripts. Remember, you need to use LuaRocks HEAD until 2.2.3 is released (due to cmake support)

**Comment by xpol** [comment]
Does the cmake_geneartor="Visual Studio 12 2013" support x64 build?

**Comment by ignacio** [comment]
Yes, it does. What LuaRocks does is to add -DCMAKE_GENERATOR_PLATFORM=x64 to the command line.

**Comment by ignacio** [comment]
I'm running some tests now. It seems that I might have missed something in the script. Please hold on :)

**Comment by xpol** [comment]
:ok_hand:

**Comment by xpol** [comment]
I think luarocks don't have `-DCMAKE_GENERATOR_PLATFORM=x64` set since https://github.com/keplerproject/luarocks/blob/master/src/luarocks/build/cmake.lua#L44 is a elseif.

**Comment by ignacio** [comment]
Thank you. That was it. I couldn't understand why it started to fail once I corrected the configuration.

https://ci.appveyor.com/project/ignacio/lua-rapidjson/build/job/eqpn24grlbx2bbyf

Give me a minute, I'll fix in LR itself.

**Comment by xpol** [comment]
My fixes [here](https://github.com/xpol/lua-rapidjson/blob/master/.scripts/install.bat#L166-L176) [works](https://ci.appveyor.com/project/xpol/lua-rapidjson/build/0.1.0.17).
But I'd like to wait you fixes to luarocks and remove the platform tail for cmake_generator.

**Comment by ignacio** [comment]
Well, thanks for the PR. I'll add that, but I think the fix must not be done in LuaRocks. When you choose the generator, you can specify if you want 64 bits, so we should not second guess the user in this case. So, that elseif is ok.

I'm polishing the fix you submitted so it adds the Win64 when necessary.

**Comment by xpol** [comment]
OK. Thank you very much @ignacio !

And I think the x64 flag should applied only once like my setup here:

https://github.com/xpol/lua-rapidjson/blob/master/.scripts/install.bat#L166-L176

Which I does not repeat my self :smile: .

Thank you for your pull request.
You are a great warm :heart: man to work with!

**Comment by ignacio** [comment]
:smile: Thanks!
